from django.utils.translation import gettext_lazy as _

MATCH_REQUEST_LOOKING_FOR_PLAYER = 1
MATCH_REQUEST_LOOKING_FOR_GROUP = 2
MATCH_REQUEST_LOOKING_FOR_CHOICES = (
    (MATCH_REQUEST_LOOKING_FOR_PLAYER, _("Player")),
    (MATCH_REQUEST_LOOKING_FOR_GROUP, _("Group")),
)

MATCH_REQUEST_RANK_ROOKIE = 1
MATCH_REQUEST_RANK_INTERMEDIATE = 2
MATCH_REQUEST_RANK_SKILLED = 3
MATCH_REQUEST_RANK_EXPERIENCED = 4
MATCH_REQUEST_RANK_EXPERT = 5
MATCH_REQUEST_RANKS = (
    (MATCH_REQUEST_RANK_ROOKIE, _("Rookie")),
    (MATCH_REQUEST_RANK_INTERMEDIATE, _("Intermediate")),
    (MATCH_REQUEST_RANK_SKILLED, _("Skilled")),
    (MATCH_REQUEST_RANK_EXPERIENCED, _("Experienced")),
    (MATCH_REQUEST_RANK_EXPERT, _("Expert")),
)
