# Generated by Django 3.1.7 on 2021-03-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_squashed_0002_auto_20201017_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='links',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='External links'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Not open yet'), (2, 'Registration open'), (4, 'Registration closed'), (8, 'Currently Running'), (16, 'Closed'), (32, 'Voting open'), (64, 'Voting closed'), (128, 'Showtime'), (256, 'Finished')], default=16),
        ),
    ]
