# Generated by Django 3.2.12 on 2022-04-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0004_competition_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="show_prestart_lock",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="If set, a pre-show lockdown will block all edits to the competition and related entries from the specified time to 'Showtime End'",
                null=True,
                verbose_name="Pre-show lockdown start",
            ),
        ),
    ]
