# Generated by Django 3.2.13 on 2022-04-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0005_competition_show_prestart_lock"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="sponsor_logo",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="sponsor"
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="sponsor_name",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
