# Generated by Django 3.2.13 on 2022-04-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0006_add_sponsor"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="vote_msg",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=140,
                null=True,
                verbose_name="Message for voting",
            ),
        ),
    ]
