# Generated by Django 3.2.16 on 2022-10-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0007_entry_vote_msg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competition",
            name="toornament",
        ),
        migrations.RemoveField(
            model_name="entry",
            name="toornament",
        ),
    ]
