# Generated by Django 4.1.7 on 2023-04-04 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0002_auto_20220415_0847'),
        ('competitions', '0009_competition_scoring_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competitions', to='core.event'),
        ),
    ]
