# Generated by Django 5.1.8 on 2025-04-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_competition_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='header_image_file',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Header Image File'),
        ),
    ]
