# Generated by Django 5.2.12 on 2026-04-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0011_competition_header_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="header_image_file",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="competition", verbose_name="Header Image File"
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="extra_info",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="Extra Info"),
        ),
    ]
