# Generated by Django 3.2.12 on 2022-03-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_squashed_0002_auto_20201017_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name_format',
            field=models.CharField(choices=[('fl', '%(first)s %(last)s'), ('lf', '%(last)s, %(first)s'), ('fla', '%(first)s %(last)s aka. %(nick)s'), ('lfa', '%(last)s, %(first)s aka. %(nick)s'), ('fa', '%(first)s aka. %(nick)s'), ('f', '%(first)s'), ('a', '%(nick)s')], default='fl', max_length=3, verbose_name='Display Name format'),
        ),
    ]
