# Generated by Django 4.1.7 on 2023-04-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_display_name_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ticket_period',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
