from django.utils.translation import ugettext_lazy as _

COMPETITION_STATE_NEW = 1
COMPETITION_STATE_REG_OPEN = 2
COMPETITION_STATE_REG_CLOSE = 4
COMPETITION_STATE_RUN = 8
COMPETITION_STATE_CLOSED = 16
COMPETITION_STATE_VOTE = 32
COMPETITION_STATE_VOTE_CLOSED = 64
COMPETITION_STATE_SHOW = 128
COMPETITION_STATE_FIN = 256
COMPETITION_STATE_CHOICES = (
    (COMPETITION_STATE_NEW, _("Not open yet")),
    (COMPETITION_STATE_REG_OPEN, _("Registration open")),
    (COMPETITION_STATE_REG_CLOSE, _("Registration closed")),
    (COMPETITION_STATE_RUN, _("Currently Running")),
    (COMPETITION_STATE_CLOSED, _("Closed")),
    (COMPETITION_STATE_VOTE, _("Voting open")),
    (COMPETITION_STATE_VOTE_CLOSED, _("Voting closed")),
    (COMPETITION_STATE_SHOW, _("Showtime")),
    (COMPETITION_STATE_FIN, _("Finished")),
)

COMPETITION_VISIBILITY_PUBLIC = "public"
COMPETITION_VISIBILITY_CREW = "crew"
COMPETITION_VISIBILITY_HIDDEN = "hidden"
COMEPTITION_VISIBILITY_CHOICES = (
    (COMPETITION_VISIBILITY_PUBLIC, _("Public")),
    (COMPETITION_VISIBILITY_CREW, _("Crew")),
    (COMPETITION_VISIBILITY_HIDDEN, _("Hidden"))
)

GENRE_CATEGORY_OTHER = "other"
GENRE_CATEGORY_CREATIVE = "creative"
GENRE_CATEGORY_GAME = "game"
GENRE_CATEGORY_COMMUNITY = "community"
GENRE_CATEGORY_TGTV = "tgtv"
GENRE_CATEGORY_SOME = "some"
GENRE_CATEGORY_CHOICES = (
    (GENRE_CATEGORY_OTHER, _("Other")),
    (GENRE_CATEGORY_CREATIVE, _("Creative")),
    (GENRE_CATEGORY_GAME, _("Game")),
    (GENRE_CATEGORY_COMMUNITY, _("Community")),
    (GENRE_CATEGORY_TGTV, _("TGTV")),
    (GENRE_CATEGORY_SOME, _("SoMe")),
)

ENTRY_STATUS_DRAFT = 1
ENTRY_STATUS_NEW = 2
ENTRY_STATUS_QUALIFIED = 4
ENTRY_STATUS_DISQUALIFIED = 8
ENTRY_STATUS_NOT_PRESELECTED = 16
ENTRY_STATUS_NOT_ALLOWED_FILE = 32
ENTRY_STATUS_CHOICES = (
    (ENTRY_STATUS_DRAFT, _("Draft")),
    (ENTRY_STATUS_NEW, _("New")),
    (ENTRY_STATUS_QUALIFIED, _("Qualified")),
    (ENTRY_STATUS_DISQUALIFIED, _("Disqualified")),
    (ENTRY_STATUS_NOT_PRESELECTED, _("Not pre-selected")),
    (ENTRY_STATUS_NOT_ALLOWED_FILE, _("Invalid file")),
)

FILE_STATUS_NEW = 1
FILE_STATUS_PREPARING = 2
FILE_STATUS_PROCESSING = 4
FILE_STATUS_FINISHED = 8
FILE_STATUS_FAILED = 16
FILE_STATUS_CHOICES = (
    (FILE_STATUS_NEW, _("New")),
    (FILE_STATUS_PREPARING, _("Preparing")),
    (FILE_STATUS_PROCESSING, _("Processing")),
    (FILE_STATUS_FINISHED, _("Finished")),
    (FILE_STATUS_FAILED, _("Failed")),
)
