# Generated by Django 3.1.2 on 2020-10-17 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("competitions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("text", models.TextField(verbose_name="description")),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Rookie"),
                            (2, "Intermediate"),
                            (3, "Skilled"),
                            (4, "Experienced"),
                            (5, "Expert"),
                        ],
                        verbose_name="rank",
                    ),
                ),
                ("role", models.TextField(verbose_name="role")),
                (
                    "looking_for",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Player"), (2, "Group")],
                        default=2,
                        verbose_name="looking for",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchrequests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchrequests",
                        to="competitions.competition",
                        verbose_name="competition",
                    ),
                ),
            ],
            options={"ordering": ("-last_updated",)},
        )
    ]
