#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $DATABASE_USER WITH PASSWORD '$DATABASE_PASSWORD';
    CREATE DATABASE $DATABASE_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $DATABASE_NAME TO $DATABASE_USER;
    ALTER DATABASE $DATABASE_NAME OWNER TO $DATABASE_USER;
    
    ALTER USER $DATABASE_USER CREATEDB;
    CREATE SCHEMA $DATABASE_USER AUTHORIZATION $DATABASE_USER;
    
    \connect $DATABASE_NAME;
    ALTER ROLE $DATABASE_USER SET client_encoding TO 'utf8';
    ALTER ROLE $DATABASE_USER SET default_transaction_isolation TO 'read committed';
    ALTER ROLE $DATABASE_USER SET timezone TO 'UTC';
EOSQL